### ISSUE TITLE
Simulation GUI design

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydra-flock-gui#2]
Current GUI design, looks something like this. I've added a grid overlay over the map to visualize the back-end grid.
![screenshot 33](https://user-images.githubusercontent.com/9114274/28746535-3a944226-74ac-11e7-9176-66f271c9126d.png)
![screenshot 38](https://user-images.githubusercontent.com/9114274/28746534-3a8f5202-74ac-11e7-95d2-9ca0aa3755aa.png)
![screenshot 39](https://user-images.githubusercontent.com/9114274/28746536-3acc9676-74ac-11e7-937e-ae6a29583dc5.png)

Once we get the drones moving, they will update their state at the central controller.
The GUI will get and maintain a list of active drones by getting the `droneCollection` from the central server. Depending upon the requirements ( how fast we want the drone position to be updated) the GUI will get drone state from the central controller for each active drone and update its position on the GUI.

If something `CRITICAL` is present in the drone state (sensor data) then we can mark that position on the map.

Drones will move based on a pure coordinate system.
@Mec-iS @chrizandr @kkoci Please provide your suggestions and reviews related to the GUI here.

**Comment by xadahiya** [comment]
There is one minor issue, currently I'm using 100Km (10x10) as area of interest with zoom level 12 but there are relatively lower number of tiles in the grid. I don't think it'll cause any problems but still we should discuss this part.

**Comment by xadahiya** [comment]
![sketch 31](https://user-images.githubusercontent.com/9114274/28747314-76380d32-74b9-11e7-9bba-3ce1d04164b2.png)
This one looks much better, I'm using a reduced tile size in GUI ( 128x128) with zoom level 12. To get tile number in the back-end we just need to use zoom level 13. Rest everything works fine

**Comment by kkoci** [comment]
I think the second version will be less laggy, we will be using google maps api right?

**Comment by xadahiya** [comment]
Yes @kkoci we're using Google maps api with gmaps.js

**Comment by Mec-iS** [comment]
As we decided to use long,lat (or according to WGS84 lat,long) the position will be given not by the tile number but by the coordinates.

**Comment by xadahiya** [comment]
@Mec-iS Yes we'll be using coordinates to update the drone position. It's just for better visualization so that the user can have some idea what's going on in the backend. Don't you think?

**Comment by Mec-iS** [comment]
First implemet a basic consistent design. Improvements are subsequent incremental additions based on feedback.

**Comment by xadahiya** [comment]
Okay, should I remove it for now then?

**Comment by Mec-iS** [comment]
For now only basic working principles, any alternative will be addressed after.

**Comment by xadahiya** [comment]
Done
