### ISSUE TITLE
Showing Datastream and other logs in the GUI

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydra-flock-gui#4]
Should logs in the GUI be persistent or should we simply keep on replacing the old logs with the new once. This one is important because there will be a LOT of logs. Please let me know what do you think @Mec-iS @kkoci @chrizandr 😄

**Comment by kkoci** [comment]
I think the approach should be replacing the old logs, but every time having the original file, for example like: hydra.log 

But also automatically creating new ones, with older logs like: hydra.log.1 , hydra.log.2, etc [0]

I think this can be achieved by using logrotate[1]

[0] https://stackoverflow.com/questions/9106795/python-logging-and-rotating-files
[1] https://support.rackspace.com/how-to/understanding-logrotate-utility/

**Comment by xadahiya** [comment]
Will take a look, thanks @kkoci 😄

**Comment by kkoci** [comment]
You are Welcome, let me know of any outcome :+1:

**Comment by xadahiya** [comment]
@kkoci Log rotate is a great tool but I don't think we need it for the simulation. As all the logs will be stored in the database itself in the central controller. What I'm asking is we have Logs and datastream sections in the GUI itself that will show the logs retrieved from the central controller. Should we display all the logs here or just last few logs.

Please let me know what you think 😄 

![sketch 33](https://user-images.githubusercontent.com/9114274/28755492-ea291e28-7579-11e7-9fbe-2fc9589a6276.png)

**Comment by Mec-iS** [comment]
Keep on the screen as many logs are necessary to display the functionality of the system. I think keeping the last 5 minutes, considering 15 secs loops, would be fine. It depends also from the number of the drones in play.

**Comment by kkoci** [comment]
We'll have to test it I think

**Comment by xadahiya** [comment]
Implemented
